const phrases = [
  { en: "Hello!", ar: "مرحباً!" },
  { en: "Good morning!", ar: "صباح الخير!" },
  { en: "Good night!", ar: "تصبح على خير!" },
  { en: "How are you?", ar: "كيف حالك؟" },
  { en: "I'm fine, thank you.", ar: "أنا بخير، شكراً لك." },
  { en: "What's your name?", ar: "ما اسمك؟" },
  { en: "My name is...", ar: "اسمي..." },
  { en: "Nice to meet you.", ar: "تشرفت بلقائك." },
  { en: "See you later.", ar: "أراك لاحقاً." },
  { en: "Goodbye!", ar: "وداعاً!" },
  { en: "Yes.", ar: "نعم." },
  { en: "No.", ar: "لا." },
  { en: "Please.", ar: "من فضلك." },
  { en: "Thank you.", ar: "شكراً لك." },
  { en: "Thank you very much.", ar: "شكراً جزيلاً لك." },
  { en: "You're welcome.", ar: "على الرحب والسعة." },
  { en: "Excuse me.", ar: "عذراً." },
  { en: "I'm sorry.", ar: "أنا آسف." },
  { en: "No problem.", ar: "لا مشكلة." },
  { en: "I don't understand.", ar: "لا أفهم." },
  { en: "Could you repeat that?", ar: "هل يمكنك تكرار ذلك؟" },
  { en: "Can you help me?", ar: "هل يمكنك مساعدتي؟" },
  { en: "I need help.", ar: "أحتاج إلى المساعدة." },
  { en: "Where is the bathroom?", ar: "أين الحمام؟" },
  { en: "How much is this?", ar: "بكم هذا؟" },
  { en: "What time is it?", ar: "كم الساعة؟" },
  { en: "Where are you from?", ar: "من أين أنت؟" },
  { en: "I'm from...", ar: "أنا من..." },
  { en: "I live in...", ar: "أعيش في..." },
  { en: "Do you speak English?", ar: "هل تتحدث الإنجليزية؟" },
  { en: "A little.", ar: "قليلاً." },
  { en: "I like it.", ar: "أعجبني." },
  { en: "I don't like it.", ar: "لا يعجبني." },
  { en: "I'm hungry.", ar: "أنا جائع." },
  { en: "I'm thirsty.", ar: "أنا عطشان." },
  { en: "I'm tired.", ar: "أنا متعب." },
  { en: "I'm lost.", ar: "أنا تائه." },
  { en: "Congratulations!", ar: "تهانينا!" },
  { en: "Happy birthday!", ar: "عيد ميلاد سعيد!" },
  { en: "Merry Christmas!", ar: "عيد ميلاد مجيد!" },
  { en: "Happy New Year!", ar: "سنة جديدة سعيدة!" },
  { en: "Good luck!", ar: "حظاً موفقاً!" },
  { en: "Bless you!", ar: "يرحمك الله!" },
  { en: "What is this?", ar: "ما هذا؟" },
  { en: "What does it mean?", ar: "ماذا يعني هذا؟" },
  { en: "What do you do?", ar: "ماذا تعمل؟" },
  { en: "I work as...", ar: "أعمل كـ..." },
  { en: "I am a student.", ar: "أنا طالب." },
  { en: "I am learning English.", ar: "أتعلم الإنجليزية." },
  { en: "I love you.", ar: "أنا أحبك." },
  { en: "I miss you.", ar: "أفتقدك." },
  { en: "Be careful.", ar: "كن حذراً." },
  { en: "Don't worry.", ar: "لا تقلق." },
  { en: "Take care.", ar: "اعتنِ بنفسك." },
  { en: "Calm down.", ar: "اهدأ." },
  { en: "Come here.", ar: "تعال هنا." },
  { en: "Go away.", ar: "اذهب بعيداً." },
  { en: "Sit down.", ar: "اجلس." },
  { en: "Stand up.", ar: "قف." },
  { en: "Hurry up!", ar: "أسرع!" },
  { en: "Wait a moment.", ar: "انتظر لحظة." },
  { en: "I agree.", ar: "أنا أوافق." },
  { en: "I disagree.", ar: "أنا لا أوافق." },
  { en: "Of course.", ar: "بالطبع." },
  { en: "Maybe.", ar: "ربما." },
  { en: "I think so.", ar: "أعتقد ذلك." },
  { en: "I don't think so.", ar: "لا أعتقد ذلك." },
  { en: "Absolutely!", ar: "تماماً!" },
  { en: "Really?", ar: "حقاً؟" },
  { en: "That's right.", ar: "هذا صحيح." },
  { en: "That's wrong.", ar: "هذا خطأ." },
  { en: "I'm ready.", ar: "أنا جاهز." },
  { en: "Are you ready?", ar: "هل أنت جاهز؟" },
  { en: "Let's go.", ar: "هيا بنا." },
  { en: "Come in.", ar: "تفضل بالدخول." },
  { en: "Close the door.", ar: "أغلق الباب." },
  { en: "Open the window.", ar: "افتح النافذة." },
  { en: "Turn on the light.", ar: "شغّل الضوء." },
  { en: "Turn off the light.", ar: "أطفئ الضوء." },
  { en: "What happened?", ar: "ماذا حدث؟" },
  { en: "What's wrong?", ar: "ما المشكلة؟" },
  { en: "It's OK.", ar: "لا بأس." },
  { en: "It's fine.", ar: "لا مشكلة." },
  { en: "I don't know.", ar: "لا أعلم." },
  { en: "Can I ask you something?", ar: "هل يمكنني أن أسألك شيئاً؟" },
  { en: "Sure.", ar: "بكل تأكيد." },
  { en: "No way!", ar: "مستحيل!" },
  { en: "Why not?", ar: "لِمَ لا؟" },
  { en: "What do you mean?", ar: "ماذا تقصد؟" },
  { en: "Who is that?", ar: "من هذا؟" },
  { en: "When?", ar: "متى؟" },
  { en: "Where?", ar: "أين؟" },
  { en: "How?", ar: "كيف؟" },
  { en: "Which one?", ar: "أيّ واحد؟" },
  { en: "Whose is this?", ar: "لِمَن هذا؟" },
  { en: "I promise.", ar: "أعدك." },
  { en: "I hope so.", ar: "آمل ذلك." },
  { en: "Don't be late.", ar: "لا تتأخر." },
  { en: "Come on!", ar: "هيا!" },
  { en: "Let's do it.", ar: "لنقم بذلك." },
  { en: "I can't wait.", ar: "لا أستطيع الانتظار." },
  { en: "Enjoy your meal!", ar: "شهية طيبة!" },
  { en: "Bon voyage!", ar: "رحلة سعيدة!" },
  { en: "Have fun!", ar: "استمتع!" },
  { en: "Good job!", ar: "عمل رائع!" },
  { en: "Well done!", ar: "أحسنت!" },
  { en: "That's enough.", ar: "هذا يكفي." },
  { en: "That's interesting.", ar: "هذا مثير للاهتمام." },
  { en: "It's amazing.", ar: "إنه رائع." },
  { en: "It's boring.", ar: "إنه ممل." },
  { en: "It's easy.", ar: "إنه سهل." },
  { en: "It's difficult.", ar: "إنه صعب." },
  { en: "I'm busy.", ar: "أنا مشغول." },
  { en: "I'm free.", ar: "أنا متفرغ." },
  { en: "I'm at work.", ar: "أنا في العمل." },
  { en: "I'm at home.", ar: "أنا في المنزل." },
  { en: "Let's meet.", ar: "لنلتقِ." },
  { en: "Call me.", ar: "اتصل بي." },
  { en: "Text me.", ar: "أرسل لي رسالة." },
  { en: "I'll be there.", ar: "سأكون هناك." },
  { en: "I have no idea.", ar: "ليست لدي فكرة." },
  { en: "That's a good idea.", ar: "إنها فكرة جيدة." },
  { en: "I'm not sure.", ar: "لست متأكداً." },
  { en: "I forgot.", ar: "لقد نسيت." },
  { en: "Never mind.", ar: "لا بأس." },
  { en: "It doesn't matter.", ar: "لا يهم." },
  { en: "Long time no see!", ar: "لم أرك منذ زمن!" },
  { en: "What's up?", ar: "ما الأخبار؟" },
  { en: "Take it easy.", ar: "تمهل." },
  { en: "See you soon.", ar: "أراك قريباً." },
  { en: "Same to you.", ar: "وأنت كذلك." },
  { en: "Absolutely not.", ar: "مستحيل إطلاقاً." },
  { en: "I'm home!", ar: "لقد عدت إلى المنزل!" },
  { en: "I'm coming.", ar: "أنا قادم." },
  { en: "One moment.", ar: "لحظة واحدة." },
  { en: "Wait for me.", ar: "انتظرني." },
  { en: "Leave me alone.", ar: "اتركني وحدي." },
  { en: "Don't touch me.", ar: "لا تلمسني." },
  { en: "Follow me.", ar: "اتبعني." },
  { en: "Let's go inside.", ar: "هيا ندخل." },
  { en: "Show me.", ar: "أرني." },
  { en: "Tell me.", ar: "أخبرني." },
  { en: "Write it down.", ar: "اكتبه." },
  { en: "Read this.", ar: "اقرأ هذا." },
  { en: "Look here.", ar: "انظر هنا." },
  { en: "Look out!", ar: "انتبه!" },
  { en: "Be quiet.", ar: "كن هادئاً." },
  { en: "Be patient.", ar: "تحلَّ بالصبر." },
  { en: "Get well soon!", ar: "شفاك الله قريباً!" },
];